CREATE TABLESPACE sensor_mgr_tablespace  
   DATAFILE 'tbs_sensor_mgr_tablespace.dbf' 
   SIZE 1m
   AUTOEXTEND ON;

CREATE USER SENSORMANAGER IDENTIFIED BY  SENSORMANAGER default TABLESPACE sensor_mgr_tablespace;
grant create session, CREATE SEQUENCE, CONNECT, resource to SENSORMANAGER;
GRANT UNLIMITED TABLESPACE TO SENSORMANAGER;
 
grant AQ_ADMINISTRATOR_ROLE to SENSORMANAGER; 
grant execute on DBMS_AQADM to SENSORMANAGER;
grant execute on DBMS_AQ to SENSORMANAGER;